title: Zahrah Aulia Putri
logo: ![zahrah](https://github.com/user-attachments/assets/8e1cf001-6715-4b9e-b301-61e3817ceb23)
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
